// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/catalog/:category/:magazineId": {
    params: {
      "category": string;
      "magazineId": string;
    };
  };
  "/terms": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/catalog/:category/:magazineId" | "/terms";
  };
  "routes/layout.tsx": {
    id: "routes/layout";
    page: "/" | "/catalog/:category/:magazineId" | "/terms";
  };
  "routes/shop.tsx": {
    id: "routes/shop";
    page: "/" | "/catalog/:category/:magazineId";
  };
  "routes/shop.index.tsx": {
    id: "routes/shop.index";
    page: "/";
  };
  "routes/shop.catalog.tsx": {
    id: "routes/shop.catalog";
    page: "/catalog/:category/:magazineId";
  };
  "routes/terms.tsx": {
    id: "routes/terms";
    page: "/terms";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/layout": typeof import("./app/routes/layout.tsx");
  "routes/shop": typeof import("./app/routes/shop.tsx");
  "routes/shop.index": typeof import("./app/routes/shop.index.tsx");
  "routes/shop.catalog": typeof import("./app/routes/shop.catalog.tsx");
  "routes/terms": typeof import("./app/routes/terms.tsx");
};