const CATALOG_WEBP_SUFFIX = '.catalog.webp';

export function assetUrl(path: string) {
  return `${import.meta.env.BASE_URL}${path.replace(/^\/+/, '')}`;
}

/** Display-resolution WebP generated by the catalog-images Vite plugin. */
export function catalogImageUrl(imagePath: string) {
  const normalized = imagePath.replace(/^\/+/, '');
  const base = normalized.replace(/\.[^./]+$/, '');
  return assetUrl(`${base}${CATALOG_WEBP_SUFFIX}`);
}
